# Generated by Django 5.2.4 on 2025-07-30 08:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Tên đăng nhập')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Bị khóa')),
                ('role', models.CharField(choices=[('g', 'GUEST'), ('u', 'USER'), ('wa', 'WEBSITE_ADMIN'), ('sa', 'SYSTEM_ADMIN')], default='u', max_length=2, verbose_name='Vai trò')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Là nhân viên')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tham gia')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Đã xác thực email')),
                ('email_verification_token', models.CharField(blank=True, max_length=255, null=True)),
                ('password_reset_token', models.CharField(blank=True, max_length=255, null=True)),
                ('password_reset_expires', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='Tên hiển thị của người dùng', max_length=255, null=True, verbose_name='Tên hiển thị')),
                ('gender', models.CharField(blank=True, choices=[('m', 'MALE'), ('f', 'FEMALE'), ('o', 'OTHER')], max_length=1, null=True, verbose_name='Giới tính')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('avatar', models.ImageField(blank=True, help_text='Ảnh đại diện của người dùng', null=True, upload_to='avatars/', verbose_name='Ảnh đại diện')),
                ('description', models.TextField(blank=True, help_text='Mô tả về bản thân', null=True, verbose_name='Mô tả')),
                ('interest', models.TextField(blank=True, help_text='Sở thích, thể loại truyện yêu thích', null=True, verbose_name='Sở thích')),
                ('is_locked', models.BooleanField(default=False, help_text='Khóa profile', verbose_name='Bị khóa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Hồ sơ người dùng',
                'verbose_name_plural': 'Hồ sơ người dùng',
            },
        ),
    ]
