# Generated by Django 5.0.6 on 2025-08-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file (mp4, webm, …) nếu không dùng YouTube URL.', null=True, upload_to='lessons/videos/', verbose_name='Video File'),
        ),
    ]
